// Mapping registry and KillList support
// For Stage 0, we only own /api/ping; extend as we implement compat endpoints.

export const ownedEndpoints = [
  '/api/ping',
  '/csrf-token',
  '/api/settings/get',
  '/api/settings/save',
  '/api/rights',
  '/api/cards/redeem',
  '/api/characters/all',
  '/api/characters/get',
  '/api/characters/create',
  '/api/characters/import-card',
  '/api/characters/export-png',
  '/api/characters/rename',
  '/api/characters/edit',
  '/api/characters/delete',
  '/api/characters/duplicate',
  '/api/characters/import',
  '/api/characters/chats',
  '/api/chats/get',
  '/api/chats/save',
  '/api/chats/recent',
  '/api/chats/search',
  '/api/chats/delete',
  '/api/chats/rename',
  '/api/files/upload',
  '/api/files/delete',
  '/api/files/verify',
  '/api/files/sanitize-filename',
  '/api/images/upload',
  '/api/images/list',
  '/api/images/delete',
  '/api/images/folders',
  '/api/backgrounds/all',
  '/api/backgrounds/upload',
  '/api/backgrounds/rename',
  '/api/backgrounds/delete',
  '/api/presets/save',
  '/api/presets/delete',
  '/api/presets/restore',
  '/api/worldinfo/get',
  '/api/worldinfo/edit',
  '/api/worldinfo/delete',
  '/api/worldinfo/import',
  '/api/extensions/discover',
  '/api/extensions/update',
  '/api/extensions/delete',
  '/api/extensions/move',
  '/api/extensions/version',
  '/api/extensions/branches',
  '/api/extensions/switch',
  '/api/extensions/install',
  '/api/search/visit',
  '/api/search/transcript',
  '/api/groups/all',
  '/api/groups/create',
  '/api/groups/edit',
  '/api/groups/delete',
  '/api/_diagnostics/state',
  '/api/_diagnostics/toggle',
  '/api/_diagnostics/radar',
];

// Endpoints that must NOT fallback in test mode (KillList)
export const killList = [
  '/api/ping',
  '/csrf-token',
  '/api/settings/get',
  '/api/settings/save',
  '/api/rights',
  '/api/cards/redeem',
  '/api/characters/all',
  '/api/characters/get',
  '/api/characters/create',
  '/api/characters/rename',
  '/api/characters/edit',
  '/api/characters/delete',
  '/api/characters/duplicate',
  '/api/characters/import',
  '/api/characters/chats',
  '/api/chats/get',
  '/api/chats/save',
  '/api/chats/recent',
  '/api/chats/search',
  '/api/chats/delete',
  '/api/chats/rename',
  '/api/files/upload',
  '/api/files/delete',
  '/api/files/verify',
  '/api/files/sanitize-filename',
  '/api/images/upload',
  '/api/images/list',
  '/api/images/delete',
  '/api/images/folders',
  '/api/backgrounds/all',
  '/api/backgrounds/upload',
  '/api/backgrounds/rename',
  '/api/backgrounds/delete',
  '/api/presets/save',
  '/api/presets/delete',
  '/api/presets/restore',
  '/api/worldinfo/get',
  '/api/worldinfo/edit',
  '/api/worldinfo/delete',
  '/api/worldinfo/import',
  '/api/extensions/discover',
  '/api/extensions/update',
  '/api/extensions/delete',
  '/api/extensions/move',
  '/api/extensions/version',
  '/api/extensions/branches',
  '/api/extensions/switch',
  '/api/extensions/install',
  '/api/search/visit',
  '/api/search/transcript',
  '/api/groups/all',
  '/api/groups/create',
  '/api/groups/edit',
  '/api/groups/delete',
  '/api/_diagnostics/state',
  '/api/_diagnostics/toggle',
  '/api/_diagnostics/radar',
  // populate as features are migrated
];

export function isOwned(pathname) {
  return ownedEndpoints.includes(pathname);
}

export function isKilled(pathname) {
  return killList.includes(pathname);
}
